#+TITLE: How To Take Smart Notes
#+ROAM_ALIAS: "HTTSN"
#+FILETAGS: :data organization:notes:zettelkasten:knowledgebase:effective thinking:thinking:

* Part 1
:PROPERTIES:
:ID:       1f1f60ff-d7d7-48c7-a811-b98160dc54a8
:END:
Your thoughts are your process - are knowledge in motion, but your thoughts are
[[file:../20200306225841-impermanent.org][impermanent]]. Notes are permanent (mostly), but they aren't animated. Smart notes
is a system that collects your thoughts, organizes them in a concerted way, and
animates them as you work with them. This takes cognitive load off of you and
clears the way for your brain to do majority processing, not majority recalling.

** 1 Introduction
:PROPERTIES:
:ID:       5a90dd37-2568-465c-8dad-579009de9f4c
:END:
Writing is thinking that outlives the biological processes. But, writing by
itself has no locomotion - it documents what was thought / done at a specific
time and place. HTTSN and Luhmann advocate for notes that evolve through
linking, a la neurons.

#+BEGIN_QUOTE
Writing is _not_ what follows research, learning or studying, it is the /medium/
of all this work. -- HTTSN
#+END_QUOTE

Longer notes:
#+begin_verse
Writing is central to academic pursuit. Even so, it is not often discussed; when
it is, focus is usually on composing large pieces (books, articles, papers,
theses). That's reasonable as those are big events, but it leaves a lack of
focus on knowledge bases and more regular writing.

Where those topics _are_ covered, it's usually in two variety:

1) Formal requirements for notes (like structure or style).
2) Psychological studies, which instruct on self-care when you write.

What books in those categories have in common is starting with a blank page --
not great, as it ignores the need for structuring as you go along. HTTSN shows
how to turn _thoughts_ and _discoveries_ into their own pieces and build a net
of rich knowledge, working and connected together.
#+end_verse

** 2 Everything you need to know
:PROPERTIES:
:ID:       daeaa646-2773-4776-8678-f16a5192b6a5
:END:
The book puts forth a notion of ideas as a first-class citizen and notes as the
constituent parts of an idea made flesh. Editing your notes and linking them
together givens them life, in a sense. You also need to utilize passion to drive
the notes -- you'll only write about what interests you in some sense.

Longer notes:
#+begin_verse
The book asks what we can do to leading up to when we need notes to prepare for
them? The oft-cited reasons for writers block and notetaking failure aren't as
strong as necessarily seems.

Ultimately, the work you produce will be predicated on the notes you create over
time. A bad notetaking flow controls you, but you can steer a good one.

Planning versus learning / working _in_ your structure: planning puts a
structure _around_ you and makes you inflexible.  This costs willpower to
maintain.

The book tries to convey that this is geared to students -- the ones with high
goals, high curiosity / drive. Bad students color in the lines and experience
Dunning-kruger effect. Good students are always looking into what they don't
know, but are likely to have impostor syndrome. /(Note: it reads a little bit
like pandering -- I mean, I have a tad more EQ than that!)/.

#+end_verse

*** Good solutions are simple - and unexpected
:PROPERTIES:
:ID:       51a2ff9a-c155-4795-b2cf-fbd116847937
:END:
Note: this slots into programming's KISS very nicely.

You need a slipbox (somewhere to store notes and a method for organizing them)
and a habit of using it.

#+BEGIN_QUOTE
The best way to deal with complexity is to keep things as simple as possible and
to follow a few basic principles. The simplicity of the structure allows
complexity to build up where we want it: on the content level. -- HTTSN
#+END_QUOTE

#+begin_verse
You aren't rebuilding everything -- you're doing things new from now on. Also,
we aren't reinventing, we're using two ideas to get things together:

1) The slipbox - storage, sure, a literal box -- but also how you work with /
   file notes in that box.
2) Building it into your routine (GTD). Getting the things in your mind out
   of your mind means you can generate more from it. What do we get from David
   Allen? You have to take the holistic perspective - shape the whole picture,
   not just the little pieces. You need a system to grown your data, like an ant
   colony.

#+end_verse
*** The Slip-box
:PROPERTIES:
:ID:       92d186bb-6fa2-42b8-ad85-f408fbfa80a3
:END:
Used by Niklas Luhmann.

When he came across something interesting, he wrote it on a note and put it
away. This wasn't working for him, though, so he flipped it into the slip-box.

He started to build out new categories for notes, linking their contexts between
them. He rearranged the notes to 'allow for dialogue'. He parlayed his notes
system from working as a public servant to becoming a professor of sociology.

#+BEGIN_QUOTE
My project: theory of society. Duration: 30 years. Costs: zero. -- Luhmann
#+END_QUOTE
"(In sociology, a "theory of society" is the mother of projects)"

Luhmann oft said approximately 'I let my slip-box think for me'.

*** The slip-box manual
:PROPERTIES:
:ID:       a97617a0-1ad6-44e2-ad33-01451d8ef84d
:END:
How does the slip-box work?

Well, there's two slip-boxes really: a bibliography and the main slipbox
containing and generating his ideas (mostly to what he's read).

Whenever he read, he would write the bibliographic info on a card and make a
brief note on the content on the flip-side. Then, he'd revisit the notes shortly
after and think about their relevance for his own thinking/writing. He'd
synthesize ideas, and write the idea, comments, thoughts on paper, only one
paper for each idea and restricting himself to one side of paper, to make it
easier without having to strip them from the box. They usually were brief enough
to fit on one sheet.

Notes can be branched off of one another (a la mercurial / git branching, with
its own numbering system), or notes can have reciporical backlinks and stored
separately (think hyperlinks / unstructured wikis). (HTTSN does say its rather
misleading to call this his own personal wikipedia, huh...). Linking notes
together allowed him to use the same data in different contexts, allowing
topical systems to develop ground-up, instead of top-down.

The last piece his system had was an index. He could use the index to pin
primers to topics.
** 3 Everything you need to do.
:PROPERTIES:
:ID:       774d86a9-cd26-47b6-8ad8-7cfa2f1b0615
:END:
Ok - imagine notetaking without a blank sheet. You have a rough draft of your
paper made out for you. You just need to revise it and send it off. There's
still work to do -- you need to edit your work, rephrase sentences, clear up
redundancies, _cultivate_ the multiplicity of ideas. But at least the work is
straightforward. Better, the preparation for the document is straightforward as
well.
** 4 Everything you need to have
:PROPERTIES:
:ID:       5cbafa52-ecda-4c31-8adb-e8fd6c149db0
:END:
Really, all you need is something to take notes in-the-moment, something to
store references in, a space to put your main notes, and something to write it
all with.

Example tools:
- Pen and paper
- zotero
- Daniel Ludecke's Zettelkasten
- An editor (one that ties to your reference manager is recommended)
* Part 2: four underlying principles
:PROPERTIES:
:ID:       1128ea99-4719-4597-bfb0-3ee03e458e29
:END:
** 5 Writing is the only thing that matters
:PROPERTIES:
:ID:       005888b7-693f-41c2-b2da-9b3a5d5fdb57
:END:
*** Tools and data are important, but more important is using them
SCHEDULED: <2020-03-07 Sat>
:PROPERTIES:
:ID:       a4faf5de-a1cc-4f7f-a5fd-b60397335074
:END:

See collectors fallacy.

*** Writing isn't a demonstration of knowledge -- writing is the knowledge itself
SCHEDULED: <2020-03-07 Sat>
:PROPERTIES:
:ID:       aae7b0ca-fcfc-4848-8efc-bba89538e814
:END:

Academic writing is driven by a topic or assignment, we're writing is a part of the process. In zettelkasten, the writing is a culmination and written record of the knowledge. Academic writing starts with a question, zettelkasten starts with knowledge _and creates the questions_.

quoting the book, studying does not prepare students for independent research, it /is/ independent research (pp 35).

This also changes how you work through academic tasks, as you restructure them around efficient learning and aiming for your notes, to "get to the point where actual open questions arise, as these are the only questions worth writing about" (Pp 37). It shifts focus in reading too: aim for the relevant above all else and read to think to synthesize new knowledge (Pp 37).
** 6 Simplicity is paramount
:PROPERTIES:
:ID:       a5ead5bf-d7ae-4c72-b988-0f6c9df8798e
:END:
Your notes live in the ZK, but there _are_ different kinds of notes:
- throw-away notes - write them, process them, trash them. For when you're busy
  or in-the-flow. /These must be acted upon, or else they expire!/

  #+BEGIN_QUOTE
If you already know that you will not go back to [the notes], don't take these
kind of notes in the first place. Take proper notes instead. (Pp. 44)
  #+END_QUOTE

- Permanent notes - they go in the box, _reference_ or _ture notes_. These are
  the important ones!

  #+BEGIN_QUOTE
    Permanent notes, on the other hand, are written in a way that can still be
    understood even when you have forgotten the context they are taken from. (Pp 44)
  #+END_QUOTE

  Ref notes are straightforward: bibliographic, referring to what was
  read/seen/heard. Main notes take curation to make them slef contained.

  #+BEGIN_QUOTE
    I make a note with the bibliographic details. On the backside I would write
    'on page x is this, on page y is that' and then it goes into the
    bibliographic slip-box where I collect everything I read. (Hagen, 1997)
    (Pp 44)
  #+END_QUOTE

  Give the context some thought in eg. your daily review.

- project notes - notes you keep around for the project, then trash.

  Workspaces help with project notes quite a bit, as you can group permanent and
  non permanent datum.

It's important to consider what trash notes to transform to permanent, what
notes are permanent vs project, what's worth keeping. And don't let yourself
overbalance in any of these.
** 7 Nobody ever starts from scratch
:PROPERTIES:
:ID:       5603cb78-8778-4e12-8029-622d3ac0b9c0
:END:
The recommended path for study is to select a topic, narrow to something to
focus on down to a single question your research and analysis will address.
HTTSN suggests going in the opposite direction.

To know where to start, and plan research, and know what to read, (to eventually
write,) you probably have to know _something_ about the topic. Don't let a
generic plan try to guide you -- let things grow out of your interests and
develop from there.

ZK means you'll have information for generating questions, as well as
information to start with -- also gives us a wider view of possible topics,
instead of a narrow, dictated view.

Brainstorming is often suggested a  kickstarter, because - lacking a durable
record, you only have your brain anyway. It's problematic as it doesn't generate
information, moreso reminds of such.
** 8 Let the work carry you forward
:PROPERTIES:
:ID:       e58c7a57-124f-4deb-af8e-45ddacd5d0a8
:END:
* 6 steps to successful writing
** 9 Separate and interlocking tasks
*** Give each task your undivided attention
*** Multitasking is not a good idea
*** Give each task the right kind of attention
*** Become an expert instead of a planner
Experts use intuition that comes from learning, versus beginners needing to work
from plans/lessons. This leads teachers to mistaking familiarity with the plan
with expertise, BTW: experts adapt, beginners are great at following the steps.

In experts, the intuition is "an incorporated history of experience" (pp. 67).

Professional academic and nonfiction writing depends on feedback loops and
experience (pp 67), and so it depends on organizing practical aspects. The
slip-box doesn't tell you what to do, it gives you the structure to do the steps
when you need to do them.
*** Get closure
We need to save our short-term memory, the stack is small (7-9 discrete items)
(pp 68). But understanding the structure of data can help with remembering data
more efficiently -- understanding _is_ learning, and [[file:../20200319165200-understanding.org][understanding]] takes place
by connecting new ideas to other ideas -- just like the Zettelkasten.

**** The Zeigarnik effect
open tasks tend to occupy our short-term memory - until they are done (pp. 70).
Externalizing information gets it out of mind and allows you to move on to the
next thing, keeping the information from weighing on you. Fortunately, you don't
need to actually finish, you just need to write down the task to help dispel it.
This is the secret to [[file:~/org/20200319170100-gtd.org][GTD]]. The slip-box has the same secret:

1) Break down the big task of writing to smaller tasks,
2) itemize and record those in your Zettelkasten,
3) write down the outcome of your thinking esp. the connections to other things
4) Noting these things gives you a chance to return to them, and ideally stores
   it in the context which you thought about them.
*** Reduce the number of decisions
Attention, memory, and now willpower. TL;DR many consecutive decisions is
straining.

:ego_depetion_defined:
"We use the term _ego depletion_ to refer
to a temporary reduction in the self's capacity or willingness to engage in
volitional action (including controlling the environment, controlling the self,
making choices, or initiating action) caused by prior exercise of volition"
(pp 72).
:end:

Many things can eat at your willpower, things that happen to you, things you do.
Because Zettelkasten is a system, it removes a lot of the need to decide by
giving you all this structure.

Worth also referring to [[file:../20200319172400-triggers.org][Triggers]], which seems to cover very similar ground.
** 10 read for understanding
Ideas to consider: Deliberate practice and context through connections.
*** 10.1 Read with a pen+paper in hand

- write literature notes with _an eye to make connections_ with your other notes -- think able this datum in the other notes context.
- Adapt lit notes to the density of the subject -- simple? you may find situations where a whole book gets a single sentence. Flip side, the more complex, the denser the lit notes.

This tends to happen with new subjects as we are dining in more with new stuff. Take those big notes, don't skip em.
- a students approach to research reading might be too tool oriented (sq3r) and not methodical or considerate of the content of the text.

_The end goal is building your thoughts and capturing them in a permanent note, not summarizing the book_.

- consider taking notes by hand: this connects with thought better. It is slower and more permanent--it requires more thoughtfulness.

*** 10.2 keep an open mind

It's common to read and only see the things that agree with you -- confirmation bias. Everyone is susceptible, but scientists and researchers are encouraged to fight it and find critical ideas and information.

We want our writing system fight confirmation bias automatically. Remember, we're trying to generate ideas from the bottom-up, so when it comes to reading we:

- ensure we understand the text and our accurate about its contents,
-then we harvest insights and connect it in context to our own notes.

In the slip box, agreement is boring--conflict is attractive.
*** 10.3 Get the Gist
Concise summary takes deliberate practice. It requires you to _read_ and
_understand_ so that you may _synthesize_ your summary.

Recognizing the patterns of not just content, but the writing strategy of the
author, helps to cycle through quickly ("circle of virtuosity: Reading becomes
easier, we grasp the gist quicker" etc (pp 83)). That said, it requires the
reader to be responsible/accountable to themselves and use their judgment when
reading. Luhmann suggests that permanent notes help train towards that; by
rewriting what you read to your own words, you're shifting from rout copying to
synthesis, focusing on:

#+begin_quote
"frames, patterns and categories in the observations,
or the conditions/assumptions, which enable certain, but not other descriptions."
#+end_quote

Remember, this note-taking is thinking made durable, so your practice spills
over to other expressions, like your spoken descriptions and general critical
thinking.
*** 10.4 Learn to read
If you can't explain it simply, you don't understand it (cf. Feynman). Permanent
notes are the same -- it just turns out you're explaining it to yourself in the
future, after you've forgotten all this crap.

Avoid 'familiarity' by reading and re-reading. Instead, as you read, record
notes and your own thoughts. This counteracts the 'exposure effect' -- where you
start associating with what you're reading, instead of just reading and
understanding. Translating your notes into permanent notes tests whether or not
you really understand it -- and again, this takes deliberate practice.
*** 10.5 Learn by reading
Learning requires deliberate practice and a concerted effort. The reason for
this is that you must understand what you're reading, which will require
thinking carefully about the text. Instead of re-reading a text for
comprehension Sonke recommends elaboration -- in this context, putting what
you've learned or understood into your own words, and connecting it to other
knowledge.

Working with a slip-box doesn't mean you put the data there and forget it.
Remember, you're sieving the knowledge through your wetware first. Instead, it's
just a external storage for accumulated datum.

In conclusion, the slipbox is an external store for the data and the connections
between them, but your brain is the think processing. Working through the
processes here will help to train both.
** 11 Take smart notes
*** Intro
When you read, try to make connections. It's useful to  read a text with the
/text's/ context in mind as well as /other/ possible contexts -- and consider
what is being left unsaid in the current context. The process of creating
permanent notes should help to encapsulate what's needed to understand that
context while providing a means for the information to stand alone.
*** 11.1 Make a career one note at a time
Many writers over the years (ie. Anthony Trollope) suggest writing with a goal
of `N` pages a day. This isn't well suited for academic or nonficiton writing.
Sonke recommends instead measuring by notes you're producing -- those represent
the sum of reading research, understanding and synthesizing.
*** 11.2 Think outside the brain
Literature notes are deliberate practice testing our undertanding of a text, and
extracting the gist into our own words more strongly checks that we understand
it. Permanent notes are a give-me-the-proof style of verification that we /know
what we're talking about/. Writing gives us the distance to judge this at least
somewhat impartially.

By writing perm. notes with an eye to your current notes, you can consider more
datum and ideas than you would be able to with your brain alone -- critical also
as the brain lies through rationalization (built for jumping to conclusions).

#+begin_quote
It is not possible to think systematically without writing (pp 94).
#+end_quote

#+begin_quote
No, it's not a record, not really. It's working. You have to work on paper, and
this is the paper. -- Feynman (pp 95)
#+end_quote

The thinking cannot be made external without connecting it.

One way to embed the notes in the slipbox's context is explicitly naming why
it's important for your own thought. Once you can state that information
plainly, you can form connections by question. For example, if you state the
importance of the topic, you can work off of 'why?' and 'is there prior art?',
'doesn't this fit with this topic', etc.

Making these questions and possible connections explicit makes the context
itself.
*** 11.3 Learn by not trying
Literature notes -- stand-alone ideas -- need to be transferred into the
slip-box context by becoming permanent notes; this also frees our mind from
holding onto that information, letting it be freer. This is important (see
Solomon Shereshevsky) as retaining that information verbatim (or close enough)
enslaves that portion of mind to retention, not elaboration/creativity. A good
goal is to shift from storage to recall -- a focus on connecting to meaningful
contexts is more likely to increase recall.
*** 11.4 Adding permanent notes to the slip-box
1. Notes should be filed behind the note that directly refers to them, or the last
   note. "The Zettelkasten" software can automatically number notes as needed
   (note: org-roam has `org-roam-insert` for cases where a new note grows from an
   old one).
2. Add links to other notes or link from the new note to other notes.
3. Make sure to add the note to the index as appropriate.
4. Build your net of mental models!
** 12 Develop Ideas
New notes in the zettelkasten should reference others, though that's not really
possible at first. When they do, you can file it behind notes. for example:

- Say you have an existent note 21, and you're filing a note behind that. You'd
  number it 22.
- However, if 22 was already created, you'd still put it behind 21 and number it
  21a.

Digital notes are easier, numbering and sequencing happen automatically.

Sequences of notes are the backbone of *text development*, blending abstract
and topic orderings.

Remember, the slip-box isn't a collection of knowledge, it's thinking. Fill gaps
where it's relevant to your project, not every hole you see.
*** 12.1 Develop topics
Once added, a note needs to be locate-able -- so we use an index. Luhmann used a
typewriter on an index card, we can use keywords. Luhmann would add 1-2 note
refs next to a given keyword on the index. Why not more? Because this isn't a
collection of notes, it's thinking -- a full index would mean more thinking on
you, instead it should be on the slip-box. The slip-box surprises because of
connections -- having a few well-selected notes in the index per-keyword is a
good enough breadcrumb, pointing from 'just a list' to interconnected ideas.

Organization of topics and subtopics comes out of our thinking and so generally
lives in the notes, too. Given that, a hierarchy of topics could just be another
note, one that is linked by the index. When it becomes stale, write a new one
and update the references to the old note (much easier with digital notes/git).

Think carefully about how you choose keywords -- don't categorize with keywords,
but point towards some other note or datum in your ZK. This can help to drive
new insight in your ZK as you file the note.

*This is important and can't be automated away -- it's thinking!*
*** 12.2 Make Smart connections
Digital tools may make links and backlinks easy, but it's still important to
think about where to make cross-references. Luhmann used 4 basic types of Xref
in his slip-box.

1. Links to *overviews* of a given topic. Usually linked from the index, it's the
   entrypoint for topics that have gotten big enough to need them. It's common to
   link to other relevant notes, usually with a short primer ("`gke` has more
   information on the open-source scheduler implementing foo", or "home tidying:
   `life-changing magic of tidying up`."). This overview can evolve over time and
   the updated version referenced from the index/the previous incarnation (Note:
   I'd think version-control would help with this, but it would hide previous
   incarnations).
2. Linking to the local cluster of notes. This is more helpful when you're
   talking pen & paper, and subtopics might be a ways away from the overview
   page.
3. links that indicate which note is a follow-up/point to the follow ups. We can
   do this automatically in the digital notes.
4. note-to-note links. They don't have the functional use of the above, but
   instead indicates connections -- 'weak links'.

 Making these links is an important part of note-taking, and fortunately there's
   a straightforward way to discover them -- walk the slip-box itself. Adding
   these links builds the slip-box -- from our thinking -- which in turn shapes
   our future thinking. Developing your thoughts means that new thoughts are
   growing among stronger datum, instead of what happens to be on your mind only.

   #+begin_quote
    The slip-box is like a well-informed but down-to-earth communication partner
    who keeps us grounded. IF we try to feed it some lofty ideas, it will force
    us to check first: What is the reference? How does that connect to the facts
    and the ideas you already have? (Pp 115)
   #+end_quote

*** 12.3 Compare, Correct and Differentiate
Because a slip-box is immutable (or durable, at least) you'll know if you
re-discover an idea. This is important as it lets you analyze with the benefit
of time and/or see if a different viewpoint (ie a different author) give you new
insight on the idea -- perhaps you can find the small differences between 2
viewpoints.

Comparison also lets us find contradictions, paradoxes, oppositions, which build
insight. Reconciliation gives you an opportunity to learn, and thus contribute
back to the slip-box and solve the problem. A paradox may mean we need more
understanding to resolve it. oppositions provide contrast and competition, which
can lead to new ideas.

Review of information can lead to scrutinizing your notes for stronger
information -- with new information, you may see your previous notes in a new
light.

Finally, the slip-box provides structure and durability that should ideally keep
us from biasing towards fresh information.
*** 12.4 Assemble a Toolbox for Thinking
Science and thinking is pragmatic -- and many mental models are surprisingly
useful in multiple, unrelated contexts. A broad toolbox for thinking is good not
just for academics but for everyday life[fn:1]. Charlie Munger (right-hand to
Warren Buffet/Berksire Hathaway) suggests searching for the most powerful
concepts and grokking them. Once integrated and used, you gain benefits from
them (eg. new insights). These are tools for learning.

These models help you learn and understand rapidly -- more so than knowing all
the facts of a thing. The structure of the slip-box encourages this by removing
the burden of memory. It also drives you through various steps that help to
forge information (elaboration) and make it useful in various contexts (spacing,
variation) whether we're looking for it (retrieval) or stumble upon it
(contextual interference).
*** 12.5 Use the Slip-Box as a Creativity Machine.

* Footnotes

[fn:1] more so as we move towards a data-driven future -- jm
